export default {
  API_URL: 'http://localhost:3000',
  CONTRACTS: 'contracts',
  EMPLOYEES: 'employees',
  HOLIDAYS: 'holidays',
  INSURANCES: 'insurances',
  MACHINES: 'machines',
  ORDERS: 'orders',
  PERMITS: 'permits',
  PERSONAL_DATA: 'personaldata',
  PRODUCTS: 'products',
  RAPORTS: 'raports',
  SALARIES: 'salaries',
  SHIFTS: 'shifts',
  SHIPPINGS: 'shippings',
  TRAININGS: 'trainings',
  USERS: 'users',
}